# Generated by Django 3.2.3 on 2021-09-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='a_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='b_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='c_count',
            field=models.IntegerField(default=0),
        ),
    ]
